language: php

php:
  - 5.6
  - 7.0
  - nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - composer require php-coveralls/php-coveralls
  - php composer.phar install -dev
  - php composer.phar dump-autoload --optimize

script:
  - mkdir ./tests/logs/
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/coveralls -v
  
matrix:
    fast_finish: true
    allow_failures:
      - php: "7.0"

addons:
    code_climate:
        repo_token: NIpWaFEWGjcB9egP2FtF3mRzS7XgP3Rzy
